In [1]:
import numpy as np

def get_svd(A):
    m, n = A.shape

    # власні вектори - праві сингулярні (V)
    ATA = A.T @ A

    eigenvalues, V = np.linalg.eigh(ATA)

    sorted_indices = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_indices]
    V = V[:, sorted_indices]

    # можуть бути від'ємні через похибку float
    singular_values = np.sqrt(np.maximum(eigenvalues, 0))

    Sigma = np.zeros((m, n))
    min_dim = min(m, n)
    Sigma[:min_dim, :min_dim] = np.diag(singular_values[:min_dim])

    # U  u_i = (A * v_i) / sigma_i
    U = np.zeros((m, m))

    for i in range(min_dim):
        if singular_values[i] > 1e-10:
            U[:, i] = (A @ V[:, i]) / singular_values[i]
        else:
            U[:, i] = np.zeros(m)

    return U, Sigma, V.T


A = np.array([
    [3, 1, 1],
    [-1, 3, 1]
])

U, S, VT = get_svd(A)

print("\nМатриця U:\n", U)
print("\nМатриця Sigma:\n", S)
print("\nМатриця V^T:\n", VT)

A_recalc = U @ S @ VT
print("\nВідновлена матриця (U * Sigma * V^T):\n", A_recalc)

print("\nРізниця:\n", A - A_recalc)


Матриця U:
 [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]

Матриця Sigma:
 [[3.46410162 0.         0.        ]
 [0.         3.16227766 0.        ]]

Матриця V^T:
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 8.94427191e-01 -4.47213595e-01  2.77555756e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]

Відновлена матриця (U * Sigma * V^T):
 [[ 3.  1.  1.]
 [-1.  3.  1.]]

Різниця:
 [[-4.44089210e-16 -8.88178420e-16 -8.88178420e-16]
 [-1.11022302e-15 -1.33226763e-15 -4.44089210e-16]]
